services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge